### ISSUE TITLE
Copy Translation to Clipboard, Translate Tooltipps

### ISSUE THREAD

**Issue by wansinby** [wbrakowski/AL-Navigator#109]
Dear Waldemar,
tnx for your translation command.
We program our extensions with a translation in comment like comment = 'DEU="Beschreibung"' for AL Translation Center (as like for AL Language Tool). Sometimes we have to copy complete Pages or Reports from the BaseApp and modify them. And in this copied pages we don't have the needed german translations, so I have to add them, e.g. using your translation command. Your command finds the translation, but I have to add them by typing, and this I would like to prevent, so here are my requests/questions:
- would it be possible to copy the translated output to the clipboard? Maybe controlled by a setting in the extension (copy translation to clipboard) or with an extra command (translate and copy)?
- is it possible to translate Tooltips too?
- do you think it would be possible to get translations for extensions like OPplus?
If you can answer my questions with yes (and improve your extension) this would really be great for us, as we could mark the english original Caption and Tooltip, translate it in Original MS Translation, an paste it in the comment.

Best regards, Wolfram

**Comment by wbrakowski** [comment]
Hello Wolfram,
thanks for the feature request.
The easiest way for me would be to create a new command "Translate and copy to clipboard" like you suggested. 
This would also work for tooltips.

I think I can ship this command within the next 2 weeks.

Translations from OPplus would be a great addition, I agree, but this would be quite some effort for me. I will consider this in the future, but for now I will only do the translations for the base app.

Best regards,
Waldemar

**Comment by wbrakowski** [comment]
Hi @wansinby,

the new command will be available within the next hours.

How to use it:

Highlight the text:

![image](https://github.com/wbrakowski/AL-Navigator/assets/53928639/6ee468ae-e9b8-433b-abe6-5ae77bd598f4)

Use the command palette:

![image](https://github.com/wbrakowski/AL-Navigator/assets/53928639/c9eaf9a7-4767-4a51-8db3-7b78dcf72d0a)

Press enter:

![image](https://github.com/wbrakowski/AL-Navigator/assets/53928639/e4c0178a-2d49-4e1e-89e3-ce568bc51c62)

**Comment by wansinby** [comment]
Dear Waldemar,
We have tested it and it works as described. Thank you very much, this will help us a lot.
Best regards, Wolfram Ansin
(BiTeam - viele Grüße von Robert Wendler)

**Comment by wbrakowski** [comment]
Thank you for the feedback :)
