### ISSUE TITLE
Copy Report Not working

### ISSUE THREAD

**Issue by kyhnel** [wbrakowski/AL-Navigator#119]
If i go to Copy Report it ask me the first question about if i want the report with or without layout, but then nothing else happens, i dont get the remaining questions it just stops, no error or anything.

this is for a BC 23 project and i have the latest VSCode installed

**Comment by wbrakowski** [comment]
Hello @kyhnel. Thanks for reporting this issue. It is related to[ another issue](https://github.com/wbrakowski/AL-Navigator/issues/118) that I just fixed. It should be working with the new version 0.5.7 of AL Navigator.

**Comment by kyhnel** [comment]
Thanks, I will check it out.

Michael
________________________________
