### ISSUE TITLE
Show Translation and copy to clipboard improvment

### ISSUE THREAD

**Issue by Hilbekale** [wbrakowski/AL-Navigator#124]
Hi, 

There is a possible improvement for the function "AL Navigator: Show translation and copy to clipboard (English -> Target Language)

It will not find a translation if you try to enter the following string:

`Specifies the document number of the original document you received from the vendor. You can require the document number for posting, or let it be optional. By default, it''s required, so that this document references the original. Making document numbers optional removes a step from the posting process. For example, if you attach the original invoice as a PDF, you might not need to enter the document number. To specify whether document numbers are required, in the Purchases & Payables Setup window, select or clear the Ext. Doc. No. Mandatory field.`

However it would find it, if you remove one of the consecutively apostrophe in the third sentence:

Instead of
` it''s`

use

` it's`

Otherwise captions or tooltips can not be translated with that function, if the caption or tooltip contains an apostrophe itself.

**Comment by wbrakowski** [comment]
@Hilbekale Thank you for reporting this. I will check this.
