### ISSUE TITLE
Word report layout no longer imports

### ISSUE THREAD

**Issue by Mainliner300** [wbrakowski/AL-Navigator#129]
When you copy the report and layout from report 1306 and then try to import the layout for the new report, an error appears regarding the report number or namespace doesn't exit. For my example my new report number is 85520. The layout is still has 1306 in it. This wasn't an issue until very recently. I would guess  that Microsoft made a change on the backend. Can you please take a look and see if there's a way to account for this? Thank you.

**Comment by wbrakowski** [comment]
@Mainliner300 Hey. Thank you for reporting this, I will fix this as soon as possible.

**Comment by wbrakowski** [comment]
@Mainliner300 Hi. I tried to reproduce this but I do not get any error. I tried it with bc version 24.3. 
Could you please provide me with the exact steps that caused your issue? 
Is it possible that the run time version in your app.json is too low and your error looks like this? In this case, you just need to increase the number in your app.json.

![image](https://github.com/user-attachments/assets/e7b9f96c-0a33-47f4-87d4-44631efdf934)
