### ISSUE TITLE
Don't add codeaction to unknown procedures

### ISSUE THREAD

**Issue by DavidFeldhoff** [wbrakowski/AL-Navigator#23]
Hi Waldemar,

If there's a procedure missing, then I don't want to have the codeaction to create a variable.

![image](https://user-images.githubusercontent.com/53570297/82179547-e2981200-98de-11ea-9f30-f69bc0af8aa0.png)

**Comment by wbrakowski** [comment]
I am aware of this problem, this will be fixed within the next few days. 
Thank you for opening the issue.

**Comment by wbrakowski** [comment]
Issue is fixed with version 0.2.8 (will be updated today).
