### ISSUE TITLE
Page Variables could also be TestPages

### ISSUE THREAD

**Issue by DavidFeldhoff** [wbrakowski/AL-Navigator#25]
If I'm in a Test-Procedure then my local Page-Variables are most likely a TestPage Variable - not a Page Variable. Maybe it's possible to add "Add local Test Page variable" and "Add local Page variable", so that I could decide what I want to choose?

**Comment by wbrakowski** [comment]
Haven't thought of this scenario. I will look into it.  :-)

**Comment by wbrakowski** [comment]
This will be fixed in the new version 0.3.0. 

Thank you for reporting!
