### ISSUE TITLE
TempRecord creates a temporary record but the name is wrong

### ISSUE THREAD

**Issue by DavidFeldhoff** [wbrakowski/AL-Navigator#26]
If I write TempSalesLine then a temporary Sales Line is created. That's cool, but the name of the variable is "SalesLine" and not "TempSalesLine" so my variable is still not declared ;)

![image](https://user-images.githubusercontent.com/53570297/82284767-12f0b680-999a-11ea-875c-3b996ad3db1c.png)

**Comment by wbrakowski** [comment]
Yes, true. Will be fixed in the next release :-)

**Comment by wbrakowski** [comment]
Issue is fixed with version 0.2.8 (will be updated today).

**Comment by achim-t** [comment]
The example in the ReadMe still shows the old behavior.

**Comment by wbrakowski** [comment]
Thanks for pointing this out. The next version will come with updated gifs.
