### ISSUE TITLE
Support for nested Variables

### ISSUE THREAD

**Issue by DavidFeldhoff** [wbrakowski/AL-Navigator#30]
Hi Waldemar, don't know if this gets a little bit more difficult, but I just tried to add a variable which is a `List[Dictionary[Code[50], Decimal]]`. The Quick Pick just asks for "List" and "Dictionary" and stops, so that I got `List[Dictionary]` which is a compiler error.
Do you think it's possible to implement?

**Comment by wbrakowski** [comment]
Wow, that is an interesting variable that you are trying to create there :)
I have no optimal way of fixing this right now, but I will definitely find one in the next weeks.

**Comment by wbrakowski** [comment]
Issue will be fixed with the next version 0.3.3.

Thanks for reporting.
