### ISSUE TITLE
Add variable - Cancel after pressing Escape

### ISSUE THREAD

**Issue by rvanbekkum** [wbrakowski/AL-Navigator#31]
Hi @wbrakowski,
After I select "Add local variable xyz" a prompt shows up that let's you select the type of the variable to create. When you cancel (e.g., pressing "Escape"), the variable is still created. Would it be possible to  abort the code-action when you cancel at this point?

**Comment by wbrakowski** [comment]
Yes, I will fix this in the next release, probably in 2-3 days. Thank you for reporting!

**Comment by wbrakowski** [comment]
This is fixed with version 0.2.9
