### ISSUE TITLE
Test Libraries are not listed in the QuickPick

### ISSUE THREAD

**Issue by DavidFeldhoff** [wbrakowski/AL-Navigator#38]
Hi Waldemar,
when I try to create a Variable of Type "Library - Varible Storage", then I don't find that one. I get the same behaviour for other Test Codeunits like "Library - Warehouse".
Do you think you can find a solution for that :) Would be awesome.

![image](https://user-images.githubusercontent.com/53570297/84650921-6a3a6600-af09-11ea-81a2-377f3bc7b888.png)

David

**Comment by wbrakowski** [comment]
Hi David,
thanks for reporting the issue. I will investigate this tomorrow

**Comment by wbrakowski** [comment]
This issue was caused because new downloaded alpackages were not being recognized. AL Navigator only loaded the packages once and did not watch for new alpackages.
It is fixed with version 0.3.2
