### ISSUE TITLE
Add a link to the marketplace entry in the README.md

### ISSUE THREAD

**Issue by dannoe** [wbrakowski/AL-Navigator#49]
You should probably link somewhere to the marketplace entry.
https://marketplace.visualstudio.com/items?itemName=wbrakowski.al-navigator

Maybe even in the about:
![grafik](https://user-images.githubusercontent.com/7450586/109639180-ca7c4100-7b46-11eb-84f2-d34baaaa5900.png)

**Comment by wbrakowski** [comment]
Hey dannoe,

that's a good idea. I tried to put it in the about section like shown on your screenshot, but it was not possible.
So I decided to put it in the readme.md for now:
![image](https://user-images.githubusercontent.com/53928639/112152096-33a12280-8be2-11eb-9c2e-1fe36fd3ef16.png)

Thank you for the idea..
