### ISSUE TITLE
Interested to demo your extension in a joined Areopa webinar?

### ISSUE THREAD

**Issue by lvanvugt** [wbrakowski/AL-Navigator#50]
Hey Waldemar ,

Are you interested in demoing your VSCode extension in a [Areopa](https://areopa.academy/) webinar?
The idea is to have AL VSCode extension domed to the community.

If you're interested please let me know. Mail to: webinars@areopa.academy.

b rg
Luc van Vugt

**Comment by wbrakowski** [comment]
Hi Luc,
sure. Sounds good :-)
I will send you an e-mail.

Kind regards,
Waldemar
