### ISSUE TITLE
Special characters in Spanish

### ISSUE THREAD

**Issue by onzema** [wbrakowski/AL-Navigator#66]
thare are some problems when "showing" some special characters in spanish.

Things like this
Input: "Buy-from Vendor No.", translation: Compra a-N&#186; proveedor -> Compra a-Nº proveedor

![image](https://user-images.githubusercontent.com/6532965/118785329-0d6dcb00-b891-11eb-8985-869485baee9e.png)

Input: Location Code, translation: C&#243;d. almac&#233;n -> Cód. almacén
![image](https://user-images.githubusercontent.com/6532965/118785527-38f0b580-b891-11eb-943b-9b9e9143aed0.png)

awesome extension!

**Comment by wbrakowski** [comment]
Hey onzema,

thank you for opening this issue. I will have a look at this and inform you when it's fixed. :-)

Kind regards

**Comment by wbrakowski** [comment]
@onzema Sorry that it took that long to fix it. In version 0.4.9 of AL Navigator all of the special characters are shown properly.
