### ISSUE TITLE
Translation not found

### ISSUE THREAD

**Issue by onzema** [wbrakowski/AL-Navigator#70]
The tooltip captions from page "warehouse pick" are not found.
![image](https://user-images.githubusercontent.com/6532965/119464256-d55c0180-bd42-11eb-9161-6bac533bc721.png)
![image](https://user-images.githubusercontent.com/6532965/119464482-0e947180-bd43-11eb-96f6-1c8877b44445.png)

I think it's because the extension only searches for captions in "dynamics nav" and this is a "Microsoft Dynamics 365 for Finance And Operations, Business Edition" Caption.

![image](https://user-images.githubusercontent.com/6532965/119464362-f4f32a00-bd42-11eb-9c3c-375b17f58246.png)

**Comment by wbrakowski** [comment]
Hey onzema,

thank you again. I honestly did not think that someone would need other translations than the ones from Dynamics NAV.
I think it would be good to have an option in the settings "target translation product". By default, this will be set to "all" so that you will see the translations from all products. If you select something else, only the translations for your selected product will be shown. 
What do you think about that? Do you have another idea?

Kind regards

**Comment by onzema** [comment]
I think the problem it's that these are some new Tooltips and are classified as "Dynamics 365 for blablabla" as "Dynamics NAV" it's the name for the "old" versions.

That said, i think your solution works great. My first option was for you to change de query to filter by these 2 products, but i think that this is no possible. At least I haven't been able to do it using the browser, when I chose more than one product it changes to "all".

Thank you for your time and great job!

**Comment by wbrakowski** [comment]
Alright. Thank you for your feedback. I will keep this issue open, maybe I can figure out a way to solve this problem.

Have a nice weekend!

**Comment by wbrakowski** [comment]
I think I found a "solution". When no translation is being found, I will give you the opportunity to search for a translation in all Microsoft products or in Dynamics 365 for Finance and Operations.

![image](https://user-images.githubusercontent.com/53928639/120311772-2c7c4c00-c2d8-11eb-9ec4-af1c0291dcb0.png)

Result:

![image](https://user-images.githubusercontent.com/53928639/120316696-fc37ac00-c2dd-11eb-99d0-dfe590783f52.png)

Hope this will work for you. It will be shipped with version 0.4.2

**Comment by onzema** [comment]
I've seen this working already! 
Thank you very much and great extension!!
