### ISSUE TITLE
New feature: Navigate to base/extended object

### ISSUE THREAD

**Issue by dannoe** [wbrakowski/AL-Navigator#79]
I often find myself scrolling up to the object definition, just to press F12 on the ``extends "XYZ"`` to go to the XYZ object.
It would be awesome if we could declare a hotkey to open the extended/base object for the current extension object.

**Comment by wbrakowski** [comment]
@dannoe Thank you for the suggestion. I will consider this but it might take a while until I will dedicate time to this project again.
