### ISSUE TITLE
Bug: Add variable

### ISSUE THREAD

**Issue by pungggi** [wbrakowski/AL-Navigator#87]
Hello I encountered a small bug with this code
![image](https://user-images.githubusercontent.com/5635709/145541229-c1a6101a-bafa-41b9-b44c-aa84133d85a0.png)

By calling Add Local Variable it added the variable to the procedure below..

![image](https://user-images.githubusercontent.com/5635709/145541355-e80cc8e3-be10-4136-babc-d60b5ef7b8c1.png)

The extension should match more accurately a minimal possible procedure signature like `procedure [text]()` and maybe exclude comments?

**Comment by wbrakowski** [comment]
Hey @pungggi Thanks for reporting this issue. I will have a look at this and inform you when it's fixed.

**Comment by wbrakowski** [comment]
@pungggi This will be fixed in version 0.5.0 by tomorrow. Thanks again and have a nic week.
