### ISSUE TITLE
Create Variable : Suggests only Page if same name is used for more objects

### ISSUE THREAD

**Issue by pungggi** [wbrakowski/AL-Navigator#88]
Hello and thank you very much, this extension is about to be my most used one!
I encountered a small bug; I am using a workaround so not important at all.

For example, you have a table called "MySetup" and a page called "MySetup".
If you start writing MySetup and then hit Ctr+. it lets you choose only a Page.
But I wanted to choose the table but did not get it as a select item.

![image](https://user-images.githubusercontent.com/5635709/145693812-5bd7dece-22ee-48c2-88ad-b3e5c6e5bc2a.png)

So, the problem seems to be an object that has the same name for a Page and a Table and maybe other object types too will be ignored for some reasons. Maybe processing stops after first hit?

btw my workaround is to use a placeholder instead of writing the variable name ahead.

**Comment by wbrakowski** [comment]
Hey @pungggi Thanks for reporting this issue and for your feedback. I will have a look at this and inform you when it's fixed. The next 2 weeks are pretty busy for me, so it might take some time.

**Comment by wbrakowski** [comment]
@pungggi  Thanks again. This will be fixed by tomorrow with release 0.5.0:

<img width="428" alt="image" src="https://user-images.githubusercontent.com/53928639/146819682-c8a35ec7-41fd-4418-9407-c570689366fc.png">
