### ISSUE TITLE
[Question] New marketplace release?

### ISSUE THREAD

**Issue by dannoe** [wbrakowski/AL-Navigator#91]
I have seen that some issues on github have been fixed and closed.
When will these fixes be released on the vs marketplace?

**Comment by wbrakowski** [comment]
Hey dannoe. The new releases are usually released within 1-2 days on the vs marketplace. Is there any specific issue that you are interested in?

**Comment by dannoe** [comment]
In [this (#87)](https://github.com/wbrakowski/AL-Navigator/issues/87#issuecomment-998166523) comment you are talking about version 0.5.0. 
The version in the marketplace is still 0.4.8

![grafik](https://user-images.githubusercontent.com/7450586/153576676-16709d63-8177-49f7-8ad9-d6eebd131023.png)

**Comment by wbrakowski** [comment]
@dannoe Uh, yes. Thanks for reminding me, I don't know why I forgot to publish the new version. It should be available in a few minutes.
![image](https://user-images.githubusercontent.com/53928639/153581331-8212e064-85d6-44e1-9d51-1a11a9235a2c.png)

**Comment by dannoe** [comment]
Thank you :)

Maybe you can setup an github action for deploying it automatically on new versions. (e.g. with https://github.com/marketplace/actions/publish-vs-code-extension)
