### ISSUE TITLE
Add Variable stopped working

### ISSUE THREAD

**Issue by nickgoddard777** [wbrakowski/AL-Navigator#97]
Hi over the last week or so the Add Variable options have stopped working.  I get the following error/callstack in the AL log and have seen that David Feldhoff has raised an issue with Microsoft about it, so I have added my call stack to that as well. 

`[Error - 09:35:34] Please report this issue to https://github.com/microsoft/al/issues including information on how to reproduce it, if possible.`
`Processing of message 'textDocument/completion' failed with error: 'Specified argument was out of the range of valid values. (Parameter 'index')'`
`Details:`
`System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'index')`
`   at Microsoft.Dynamics.Nav.CodeAnalysis.Text.SourceText.LineInfo.get_Item(Int32 index) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Text\SourceText.cs:line 661`
`   at Microsoft.Dynamics.Nav.CodeAnalysis.Text.TextLineCollection.GetPosition(LinePosition position) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Text\TextLineCollection.cs:line 81`
`   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.CompletionRequestHandler.HandleAsync(CompletionRequest request, Int32 requestId, CancellationToken cancellationToken) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\CompletionRequestHandler.cs:line 45`
`   at Microsoft.Dynamics.Nav.EditorServices.Protocol.MessageProtocol.RequestHandlerBase``1.HandleAsync(JToken requestContents, Int32 requestId, CancellationToken cancellationToken) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\MessageProtocol\RequestHandlerBase.cs:line 103`
`   at Microsoft.Dynamics.Nav.EditorServices.Protocol.RequestRegistry.Process(Message message) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Endpoints\RequestRegistry.cs:line 108`

**Comment by wbrakowski** [comment]
Hey @nickgoddard777. Thanks for reporting this. I will check it but it might take a while.

**Comment by wbrakowski** [comment]
@nickgoddard777 Do you still have this error? I could not reproduce it.
