### ISSUE TITLE
AL Language Server Crashing - temp-al-proxy.al

### ISSUE THREAD

**Issue by pri-kise** [wbrakowski/AL-Navigator#99]
I created an issue for the AZ AL Dev Tools Extension.
https://github.com/anzwdev/al-code-outline/issues/385
The file temp-al-proxy.al results in some strange errors when downloading symbols.

In the referenced issue, the developer mentioned that this extension might produces this file, too.
Maybe you can have a look at some time and try to remove the usage of this file, too.

**Comment by wbrakowski** [comment]
@pri-kise Thank you for reporting the issue. I will investigate this, but at the moment I don't have a lot of time to do it. So it might take a while.

**Comment by wbrakowski** [comment]
As long as this keeps working, I do not see a reason to fix it. If this becomes a problem in the future, I will reopen.
